# Generated by Django 2.2.15 on 2020-08-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200814_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='default.png', upload_to='blog_images/'),
        ),
    ]
